### ISSUE TITLE
Child-theme style.css not appearing in page source

### ISSUE THREAD

**Issue by 34tth3r1ch** [ThemeButler/tbr-banks#1]
I have Banks installed as a child-theme of Beans. The style.css file within the Banks theme directory, though sending theme data to the Appearance page, does not appear in the page source when viewing the site... any reason why?

**Comment by 34tth3r1ch** [comment]
Realized how the theme is configured. The style.css is a placeholder for the theme information. Styling is done using style.less from within the **assets > less** directory.

**Comment by smokeyfro** [comment]
@pilgrimish Sorry, only saw this now. I had my notifications set to an email address I don't frequently check. I've updated to my current one, so will see any new issues as they come in. 

Yeah, the style.css is purely to provide the theme info for WordPress. You can however easily include it via the assets/assets.php, if you prefer vanilla css over less. Of course the style.less also supports normal css too.

Cheers :)
